# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scaffolder-annotation-locator}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Barton"]
  s.date = %q{2011-04-05}
  s.description = %q{Build a genome scaffold using scaffolder and a set of annotated contigs. This tool updates the locations of the contig annotations using the scaffolder tempalte as a base.}
  s.email = %q{mail@michaelbarton.me.uk}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/gff3.feature",
    "features/step_definitions/scaffolder-annotation-locator_steps.rb",
    "features/support/env.rb",
    "lib/scaffolder/annotation_locator.rb",
    "scaffolder-annotation-locator.gemspec",
    "spec/scaffolder/annotation_locator_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/gff_attribute_matcher.rb"
  ]
  s.homepage = %q{http://next.gs}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Update locations of gff3 annotations from a scaffolder template}
  s.test_files = [
    "spec/scaffolder/annotation_locator_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/gff_attribute_matcher.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<scaffolder>, ["~> 0.4"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5"])
      s.add_development_dependency(%q<rspec>, ["~> 2.4"])
      s.add_development_dependency(%q<scaffolder-test-helpers>, ["= 0.2.2"])
      s.add_development_dependency(%q<cucumber>, ["~> 0.9"])
      s.add_development_dependency(%q<aruba>, ["~> 0.2"])
      s.add_development_dependency(%q<yard>, ["~> 0.6"])
    else
      s.add_dependency(%q<scaffolder>, ["~> 0.4"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5"])
      s.add_dependency(%q<rspec>, ["~> 2.4"])
      s.add_dependency(%q<scaffolder-test-helpers>, ["= 0.2.2"])
      s.add_dependency(%q<cucumber>, ["~> 0.9"])
      s.add_dependency(%q<aruba>, ["~> 0.2"])
      s.add_dependency(%q<yard>, ["~> 0.6"])
    end
  else
    s.add_dependency(%q<scaffolder>, ["~> 0.4"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5"])
    s.add_dependency(%q<rspec>, ["~> 2.4"])
    s.add_dependency(%q<scaffolder-test-helpers>, ["= 0.2.2"])
    s.add_dependency(%q<cucumber>, ["~> 0.9"])
    s.add_dependency(%q<aruba>, ["~> 0.2"])
    s.add_dependency(%q<yard>, ["~> 0.6"])
  end
end

